<?xml version="1.0" encoding="UTF-8"?>
<!-- UPS Freight Rate Service WSDL Release Date Dec 29, 2007 -->
<!-- Copyright 2007-2008 United Parcel Service of America, Inc. All rights reserved.   -->
<wsdl:definitions name="FreightRate" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:error="http://www.ups.com/XMLSchema/XOLTWS/Error/v1.1" xmlns:upss="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0" xmlns:frt="http://www.ups.com/XMLSchema/XOLTWS/FreightRate/v1.0" xmlns:tns="http://www.ups.com/WSDL/XOLTWS/FreightRate/v1.0" targetNamespace="http://www.ups.com/WSDL/XOLTWS/FreightRate/v1.0">
	<wsdl:types>
		<xsd:schema>
			<!-- This schema defines the UPS Security header used for authorization purposes -->
			<xsd:import namespace="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0" schemaLocation="UPSSecurity.xsd"/>
			<!--  This schema defines the error detail data types returned within SOAPFaults to provide more specific information pertaining to the problem. -->
			<xsd:import namespace="http://www.ups.com/XMLSchema/XOLTWS/Error/v1.1" schemaLocation="Error1.1.xsd"/>
			<!-- start :FreightRate schema -->
			<xsd:import namespace="http://www.ups.com/XMLSchema/XOLTWS/FreightRate/v1.0" schemaLocation="FreightRateWebServiceSchema.xsd"/>
			<!-- end : List of complex types used by FreightRate schema -->
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="RateRequestMessage">
		<wsdl:part name="Body" element="frt:FreightRateRequest"/>
		<wsdl:part name="UPSSecurity" element="upss:UPSSecurity"/>
	</wsdl:message>
	<wsdl:message name="RateResponseMessage">
		<wsdl:part name="Body" element="frt:FreightRateResponse"/>
	</wsdl:message>
	<wsdl:message name="RateErrorMessage">
		<wsdl:part name="RateError" element="error:Errors"/>
	</wsdl:message>
	<wsdl:portType name="FreightRatePortType">
		<wsdl:operation name="ProcessFreightRate">
			<wsdl:input name="RateRequest" message="tns:RateRequestMessage"/>
			<wsdl:output name="RateResponse" message="tns:RateResponseMessage"/>
			<wsdl:fault name="RateError" message="tns:RateErrorMessage"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="FreightRateBinding" type="tns:FreightRatePortType">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="ProcessFreightRate">
			<soap:operation soapAction="http://onlinetools.ups.com/webservices/FreightRateBinding/v1.0" style="document"/>
			<wsdl:input name="RateRequest">
				<soap:body parts="Body" use="literal"/>
				<soap:header message="tns:RateRequestMessage" part="UPSSecurity" use="literal">
					<soap:headerfault message="tns:RateErrorMessage" part="RateError" use="literal"/>
				</soap:header>
			</wsdl:input>
			<wsdl:output name="RateResponse">
				<soap:body parts="Body" use="literal"/>
			</wsdl:output>
			<wsdl:fault name="RateError">
				<soap:fault name="RateError" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="FreightRateService">
		<wsdl:port name="FreightRatePort" binding="tns:FreightRateBinding">
			<!-- Production URL -->
			<!-- <soap:address location="https://onlinetools.ups.com/webservices/FreightRate"/> -->
			<!-- CIE (Customer Integration Environment) URL -->
			<soap:address location="https://wwwcie.ups.com/webservices/FreightRate"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
