<?xml version="1.0" encoding="UTF-8"?>
<!-- UPS Freight Ship Service WSDL Release Date Dec 29, 2007 -->
<!-- Copyright 2007-2008 United Parcel Service of America, Inc. All rights reserved.   -->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:error="http://www.ups.com/XMLSchema/XOLTWS/Error/v1.1" xmlns:upss="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0" xmlns:fsp="http://www.ups.com/XMLSchema/XOLTWS/FreightShip/v1.0" xmlns:tns="http://www.ups.com/WSDL/XOLTWS/FreightShip/v1.0" targetNamespace="http://www.ups.com/WSDL/XOLTWS/FreightShip/v1.0">
	<wsdl:types>
		<xsd:schema>
			<!-- This schema defines the UPS Security header used for authorization purposes -->
			<xsd:import namespace="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0" schemaLocation="UPSSecurity.xsd"/>
			<!--  This schema defines the error detail data types returned within SOAPFaults to provide more specific information pertaining to the problem. -->
			<xsd:import namespace="http://www.ups.com/XMLSchema/XOLTWS/Error/v1.1" schemaLocation="Error1.1.xsd"/>
			<!-- This schema defines the Freight Ship service data types -->
			<xsd:import namespace="http://www.ups.com/XMLSchema/XOLTWS/FreightShip/v1.0" schemaLocation="FreightShipWebServiceSchema.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="ShipRequestMessage">
		<wsdl:part name="Body" element="fsp:FreightShipRequest"/>
		<wsdl:part name="UPSSecurity" element="upss:UPSSecurity"/>
	</wsdl:message>
	<wsdl:message name="ShipResponseMessage">
		<wsdl:part name="Body" element="fsp:FreightShipResponse"/>
	</wsdl:message>
	<wsdl:message name="ShipErrorMessage">
		<wsdl:part name="ShipError" element="error:Errors"/>
	</wsdl:message>
	<wsdl:portType name="FreightShipPortType">
		<wsdl:operation name="ProcessShipment">
			<wsdl:input name="ShipRequest" message="tns:ShipRequestMessage"/>
			<wsdl:output name="ShipResponse" message="tns:ShipResponseMessage"/>
			<wsdl:fault name="ShipError" message="tns:ShipErrorMessage"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="FreightShipBinding" type="tns:FreightShipPortType">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="ProcessShipment">
			<soap:operation soapAction="http://onlinetools.ups.com/webservices/FreightShipBinding/v1.0" style="document"/>
			<wsdl:input name="ShipRequest">
				<soap:body parts="Body" use="literal"/>
				<soap:header message="tns:ShipRequestMessage" part="UPSSecurity" use="literal">
					<soap:headerfault message="tns:ShipErrorMessage" part="ShipError" use="literal"/>
				</soap:header>
			</wsdl:input>
			<wsdl:output name="ShipResponse">
				<soap:body parts="Body" use="literal"/>
			</wsdl:output>
			<wsdl:fault name="ShipError">
				<soap:fault name="ShipError" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="FreightShipService">
		<wsdl:port name="FreightShipPort" binding="tns:FreightShipBinding">
			<!-- Production URL -->
			<!-- <soap:address location="https://onlinetools.ups.com/webservices/FreightShip"/> -->
			<!-- CIE (Customer Integration Environment) URL -->
			<soap:address location="https://wwwcie.ups.com/webservices/FreightShip"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
